# Modified Release github action. Replace the current with this when ready.
name: Release New

on:
  push:
    tags:
      - '*' 

jobs:
  release-new:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo add-apt-repository -y ppa:dysfunctionalprogramming/minisign
          sudo apt update
          sudo apt install -yq build-essential zip minisign
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build Linux
        run: cargo xtask dist
      - name: Sign files
        run: |
          echo -e $MINISIGN_KEY > minisign.key 
          echo $MINISIGN_PASSWORD | minisign -Sm target/dist/phylum-linux-x86_64/phylum -s minisign.key -t 'Phylum - Future of software supply chain security'
          echo $MINISIGN_PASSWORD | minisign -Sm target/dist/phylum-macos-x86_64/phylum -s minisign.key -t 'Phylum - Future of software supply chain security'
          echo $MINISIGN_PASSWORD | minisign -Sm target/dist/phylum-macos-aarch64/phylum -s minisign.key -t 'Phylum - Future of software supply chain security'
        env:
          MINISIGN_KEY: ${{ secrets.MINISIGN_KEY }}
          MINISIGN_PASSWORD: ${{ secrets.MINISIGN_PASSWORD }}
      - name: Build zipfile
        working-directory: ./target/dist
        run: |
          zip -r phylum-linux-x86_64 phylum-linux-x86_64 
          zip -r phylum-macos-x86_64 phylum-macos-x86_64 
          zip -r phylum-macos-aarch64 phylum-macos-aarch64 
