name = "npm"
description = "NPM package manager hooks"
entry_point = "main.ts"

[permissions]
write = ["./package-lock.json", "./package.json"]
read = ["./package-lock.json", "./package.json"]
run = ["npm"]
