name = "yarn"
description = "yarn package manager hooks"
entry_point = "main.ts"

[permissions]
write = ["/tmp", "~/.cache/node", "~/.cache/yarn", "~/.yarn", "./"]
read = true
run = ["yarn", "/tmp"]
net = true
