name = "yarn"
description = "yarn package manager hooks"
entry_point = "main.ts"

[permissions]
write = ["~/.cache/node", "~/.cache/yarn", "~/.yarn", "./"]
read = ["~/.cache/node", "~/.cache/yarn", "~/.yarn", "./"]
run = ["yarn"]
