[package]
name = "vulnreach_types"
version = "0.1.0"
authors = ["Veracode, Inc. <dl-phylum-engineering@veracode.com>"]
edition = "2021"
rust-version = "1.85.0"

[dependencies]
serde = { version = "1.0.152", features = ["derive"] }
