FROM rust:1.58.1-slim-buster

RUN apt-get update && apt-get install -y musl-tools
RUN rustup target add x86_64-unknown-linux-musl

WORKDIR /build/cli
COPY . .

RUN cargo build --release --target x86_64-unknown-linux-musl
