# Workflow for updating Rust dependencies with Cargo and Javascript dependencies with npm.
# Major version updates are handled separately, by Dependabot.
---
name: Update Deps

on:
  workflow_dispatch:
  # Run every Monday at 0530 UTC
  schedule:
    - cron: '30 5 * * 1'

jobs:
  workflow-auto-updates:
    name: Update dependencies
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout the repo
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Set up Node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: website/package-lock.json

      - name: Update CLI Rust dependencies
        run: cargo update

      - name: Update Docusaurus Javascript dependencies
        working-directory: ./website
        run: npm update --save

      - name: Commit changes
        id: commit
        continue-on-error: true
        run: |
          git config user.name 'phylum-bot'
          git config user.email '69485888+phylum-bot@users.noreply.github.com'
          git commit -a -m "build: bump Rust and Javascript dependencies"
          git push --force origin HEAD:workflow-auto-updates

      - name: Create Pull Request
        if: ${{ steps.commit.outcome == 'success' }}
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        with:
          # This PAT is for the `phylum-bot` account and only has the `public_repo` scope to limit privileges.
          github-token: ${{ secrets.GH_RELEASE_PAT }}
          script: |
            const response = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: "workflow-auto-updates",
              base: context.ref,
              title: "build: bump Rust and Javascript dependencies",
              body: "Bump dependencies in `Cargo.lock` and `website/package-lock.json` "
                  + "for all SemVer-compatible updates.",
            });
            console.log(response);
