---
name: Update Deps

on:
  workflow_dispatch:
  # Run every Monday
  schedule:
    - cron: '30 5 * * 1'

jobs:
  cargo-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Cargo update
        run: cargo update

      - name: Commit changes
        id: commit
        continue-on-error: true
        run: |
          git config user.name 'phylum-bot'
          git config user.email '69485888+phylum-bot@users.noreply.github.com'
          git commit -a -m "Bump dependencies"
          git push --force origin HEAD:auto-cargo-update

      - name: Create Pull Request
        if: ${{ steps.commit.outcome == 'success' }}
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          github-token: ${{ secrets.GH_RELEASE_PAT }}
          script: |
            github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: "auto-cargo-update",
              base: context.ref,
              title: "Bump dependencies",
              body: "Bump dependencies for all SemVer-compatible updates.",
            });
